name: Run main.py every Saturday

on: 
  schedule:
    - cron: '0 19 * * 5'

jobs:
  run-main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'   # Replace 'x' with your desired Python version

    - name: Install dependencies
      run: pip install -r requirements.txt  # If you have any dependencies, create a requirements.txt file and list them here

    - name: Run main.py
      run: python main.py
  
    - name: Commit changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add .  # This will stage all the changes, including the JSON file created by main.py
        git commit -m "Add generated JSON file"
        git push origin HEAD
